### ISSUE TITLE
Official vanilla model performs terribly in Image-Textual Classification Task

### ISSUE THREAD

**Issue by Z1zs** [franciscoliu/MLLMU-Bench#2]
Thank you very much for your amazing work! 

Currently I'm trying to reproduce the results reported in the paper. I downloaded the weights from [vanilla repo](https://hf-mirror.com/MLLMMU/LLaVA_Vanilla) and ran
`python eval.py --model_id llava-hf/llava-1.5-7b-hf --cache_path /data/models/LLaVA_Vanilla --test_data data/MLLMU-Bench/Test_Set --few_shot_data data/MLLMU-Bench/Full_Set/train-00000-of-00001.parquet --data_split_folder data/MLLMU-Bench --celebrity_data data/MLLMU-Bench/Retain_Set/train-00000-of-00001.parquet --output_file llava-1.5-7b-vanilla --output_folder ../eval_result/llava_7b_hf_vanilla_test2 --forget_ratio 5`

to evaluate the performance of vanilla model. Unfortunately, it turned out to perform very poorly in  `Image-Textual Classification Task` , and the results are shown below:

> {
>     "Forget Set Results": {
>         "fill_in_the_blank": {
>             "image_textual_accuracy": 13.043478260869565,
>             "pure_text_accuracy": 15.217391304347828
>         },
>         "classification": {
>             "Image-Textual Question Accuracy": 0.0,
>             "Pure Text Question Accuracy": 58.26086956521739
>         },
>         "generation": {
>             "Average ROUGE-1 (Image_Textual)": 0.5302813722225488,
>             "Average ROUGE-2 (Image_Textual)": 0.37959408719935034,
>             "Average ROUGE-L (Image_Textual)": 0.5302813722225488,
>             "Average BLEU (Image_Textual)": 0.21443110848259012,
>             "Average ROUGE-1 (Pure_Text)": 0.6416706777764795,
>             "Average ROUGE-2 (Pure_Text)": 0.4604978942626001,
>             "Average ROUGE-L (Pure_Text)": 0.6416706777764795,
>             "Average BLEU (Pure_Text)": 0.31048326670287624
>         }
>     },
>     "Test Set Results": {
>         "fill_in_the_blank": {
>             "image_textual_accuracy": 21.73913043478261,
>             "pure_text_accuracy": 15.217391304347828
>         },
>         "classification": {
>             "Image-Textual Question Accuracy": 0.0,
>             "Pure Text Question Accuracy": 41.73913043478261
>         },
>         "generation": {
>             "Average ROUGE-1 (Image_Textual)": 0.2117990767402532,
>             "Average ROUGE-2 (Image_Textual)": 0.12216305916305918,
>             "Average ROUGE-L (Image_Textual)": 0.2117990767402532,
>             "Average BLEU (Image_Textual)": 0.06587699403277916,
>             "Average ROUGE-1 (Pure_Text)": 0.523886344019471,
>             "Average ROUGE-2 (Pure_Text)": 0.3646427278603749,
>             "Average ROUGE-L (Pure_Text)": 0.5182567143898412,
>             "Average BLEU (Pure_Text)": 0.22179174422799441
>         }
>     },
>     "Retain Set (shared dataset) Results": {
>         "fill_in_the_blank": {
>             "image_textual_accuracy": 26.109936575052856,
>             "pure_text_accuracy": 15.856236786469344
>         },
>         "classification": {
>             "Image-Textual Question Accuracy": 0.0,
>             "Pure Text Question Accuracy": 44.237288135593225
>         },
>         "generation": {
>             "Average ROUGE-1 (Image_Textual)": 0.42957617691782707,
>             "Average ROUGE-2 (Image_Textual)": 0.29419894118322004,
>             "Average ROUGE-L (Image_Textual)": 0.4243630142960724,
>             "Average BLEU (Image_Textual)": 0.17189566997724495,
>             "Average ROUGE-1 (Pure_Text)": 0.6654823322520478,
>             "Average ROUGE-2 (Pure_Text)": 0.5215762148108634,
>             "Average ROUGE-L (Pure_Text)": 0.6620983057119415,
>             "Average BLEU (Pure_Text)": 0.3787960145572746
>         }
>     },
>     "Retain Set (real person) Results": {
>         "fill_in_the_blank": {
>             "image_textual_accuracy": 10.784313725490197,
>             "pure_text_accuracy": 19.28104575163399
>         },
>         "classification": {
>             "Image-Textual Question Accuracy": 47.911227154047,
>             "Pure Text Question Accuracy": 56.33986928104575
>         },
>         "generation": {
>             "Average ROUGE-1 (Image_Textual)": 0.22716330071835802,
>             "Average ROUGE-2 (Image_Textual)": 0.10221513198694562,
>             "Average ROUGE-L (Image_Textual)": 0.21772507565049148,
>             "Average BLEU (Image_Textual)": 0.05687700866966418,
>             "Average ROUGE-1 (Pure_Text)": 0.6046668909897491,
>             "Average ROUGE-2 (Pure_Text)": 0.4546217877819915,
>             "Average ROUGE-L (Pure_Text)": 0.5937276674039785,
>             "Average BLEU (Pure_Text)": 0.2849095572023093
>         }
>     }
> }

I'm not sure if there are anything wrong with my settings, or have you just reported the `Pure Text Question Accuracy` in your paper? Any feedback will be appreciated, thanks again for your works!

**Comment by franciscoliu** [comment]
I've just obtained the result on my end about the vanilla model, which seems reasonable at my end. I will need more details about your settings to further investigate your problem. However, I've just re-uploaded the vanilla model to just to make sure it is consistent with my version. Could you test it and see if your problem has been solved? If the problem persists, you are also welcomed to provide more details to my personal email: zliu29@nd.edu. Let me know how it goes! : )

**Comment by Z1zs** [comment]
Sorry for the late reply.

Although I haven't totally confirmed the root of this problem, I suspect it's related to the long context resulting from too much few shot examples for llava. By changing [Line 265 in `eval.py`](https://github.com/franciscoliu/MLLMU-Bench/blob/60cd3c765ad4cf43753073a558075884a3c23709/eval.py#L265) to `selected_ids = random.sample(id_list, 1)`, I have got reasonable outputs.

Output before the change:
```
......
USER:  
What is this person's primary activity in the image?
A: Working in a tech startup
B: Attending school
C: Painting
D: Playing with a pet
Just give ONE letter representing the answer directly.
ASSISTANT: US US US US US US US US US US US US US US US US US US US US US US US US US
```

Output after the change:
```
......
USER:  
What hobby is likely depicted in this image of the person?
A: Coding
B: Painting
C: Playing sports
D: Collecting stamps
Just give ONE letter representing the answer directly.
ASSISTANT: A 
```

Would like to report the complete eval results later. I'm also glad to submit a PR if this adjustment is confirmed to be correct.

**Comment by franciscoliu** [comment]
Thanks for the reply! Yes, the modification you proposed will change the number of few shot examples feed to the model during evaluation, which is a simple change. I will probably make this to a hyper parameter later to facilitate other people. But thanks for pointing this out. And yes, the number of few shot examples can significantly influence the evaluation performance of the model as it showcases model what an ideal answer format would look like. Plus, during the evaluation, we exclude the evaluation of those selected few shot examples to make sure a fair evaluation.

**Comment by Z1zs** [comment]
@franciscoliu Thanks for the replay!
I have tested the performance of vanilla model on Forget5, 10, 15 Set, and get the results:

```
# forget5
{
    "Forget Set Results": {
        "fill_in_the_blank": {
            "image_textual_accuracy": 15.217391304347828,
            "pure_text_accuracy": 17.391304347826086
        },
        "classification": {
            "Image-Textual Question Accuracy": 37.5,
            "Pure Text Question Accuracy": 43.333333333333336
        },
        "generation": {
            "Average ROUGE-1 (Image_Textual)": 0.5781975834622894,
            "Average ROUGE-2 (Image_Textual)": 0.41837889449731547,
            "Average ROUGE-L (Image_Textual)": 0.5708306366835779,
            "Average BLEU (Image_Textual)": 0.24219108440747608,
            "Average ROUGE-1 (Pure_Text)": 0.6418485863981221,
            "Average ROUGE-2 (Pure_Text)": 0.4638885036532096,
            "Average ROUGE-L (Pure_Text)": 0.6418485863981221,
            "Average BLEU (Pure_Text)": 0.30147499767870456
        }
    }
}
# forget 10
{
    "Forget Set Results": {
        "fill_in_the_blank": {
            "image_textual_accuracy": 34.375,
            "pure_text_accuracy": 29.166666666666668
        },
        "classification": {
            "Image-Textual Question Accuracy": 42.04081632653061,
            "Pure Text Question Accuracy": 42.44897959183673
        },
        "generation": {
            "Average ROUGE-1 (Image_Textual)": 0.51050058217136,
            "Average ROUGE-2 (Image_Textual)": 0.3762803928898731,
            "Average ROUGE-L (Image_Textual)": 0.5058239275566246,
            "Average BLEU (Image_Textual)": 0.2524123044914247,
            "Average ROUGE-1 (Pure_Text)": 0.6752239564212777,
            "Average ROUGE-2 (Pure_Text)": 0.5292761889342316,
            "Average ROUGE-L (Pure_Text)": 0.6689668250663203,
            "Average BLEU (Pure_Text)": 0.39240830691314904
        }
    }
}
# forget 15
{
    "Forget Set Results": {
        "fill_in_the_blank": {
            "image_textual_accuracy": 24.65753424657534,
            "pure_text_accuracy": 15.753424657534246
        },
        "classification": {
            "Image-Textual Question Accuracy": 48.37837837837838,
            "Pure Text Question Accuracy": 43.24324324324324
        },
        "generation": {
            "Average ROUGE-1 (Image_Textual)": 0.48710259232034225,
            "Average ROUGE-2 (Image_Textual)": 0.34454114398510693,
            "Average ROUGE-L (Image_Textual)": 0.4822324953836819,
            "Average BLEU (Image_Textual)": 0.18616204808147394,
            "Average ROUGE-1 (Pure_Text)": 0.6652699981793077,
            "Average ROUGE-2 (Pure_Text)": 0.5298330482574034,
            "Average ROUGE-L (Pure_Text)": 0.6615141984235078,
            "Average BLEU (Pure_Text)": 0.3864866076238791
        }
    }
}
```
Could you please check the results to see if they're consistent with yours? 

What's more, I'm still a little unclear about the meaning between Forget Set, Test Set, Retain Shared Set. Could you please further explain the difference? Thanks a lot!

**Comment by Z1zs** [comment]
Thank you very much for your kindly reply! My question has been perfectly answered.

**Comment by Z1zs** [comment]
I'm sorry but when I run the baselines I got the error
`cannot import name 'LLAVA_multimodal_Dataset' from 'data_process.data_preprocess'`

Could you please kindly release the implementation of "LLAVA_multimodal_Dataset"?

**Comment by franciscoliu** [comment]
Thank you for the reminder, just updated it there : )
